
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-client-certs
spec:
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: kafka-client-certs
  dataFrom:
    - extract:
        key: msk-client-cert
